load('//js:def.bzl', 'js_binary')

js_binary(
  name = 'npm_install_config',
  src  = 'npm_install_config.js',
)

# py_binary(
#   name = 'npm_to_js_library',
#   srcs = ['npm_to_js_library.py'],
#   srcs_version = 'PY2AND3',
# )
