load(':typescript_compiler.bzl', 'typescript_compiler')


typescript_compiler(
  name = 'default_compiler',
  arguments = [
    '--declaration',
    '--strict',
  ],
  visibility = ['//visibility:public'],
)
