load('//js:def.bzl', 'npm_tarball_install')

def browserify_repositories():
  """
  TODO: This is kinda gross
  """
  npm_tarball_install(
    name = 'browserify',
    url = 'https://s3.amazonaws.com/js.vistarmedia.com/browserify-14.4.0.tgz',
    sha256 = 'deafadbb88c976fb2bf41e911dfc0a70e635a4073f1c8c49549eb964e96f9d62',
    ignore_deps = [
      'JSONStream',
      'assert',
      'browser-pack',
      'browser-resolve',
      'browserify-zlib',
      'buffer',
      'cached-path-relative',
      'concat-stream',
      'console-browserify',
      'constants-browserify',
      'crypto-browserify',
      'defined',
      'deps-sort',
      'domain-browser',
      'duplexer2',
      'events',
      'glob',
      'has',
      'htmlescape',
      'https-browserify',
      'inherits',
      'insert-module-globals',
      'labeled-stream-splicer',
      'module-deps',
      'os-browserify',
      'parents',
      'path-browserify',
      'process',
      'punycode',
      'querystring-es3',
      'read-only-stream',
      'readable-stream',
      'resolve',
      'shasum',
      'shell-quote',
      'stream-browserify',
      'stream-http',
      'string_decoder',
      'subarg',
      'syntax-error',
      'through2',
      'timers-browserify',
      'tty-browserify',
      'url',
      'util',
      'vm-browserify',
      'xtend',
    ]
  )
